import "./src/styles/global.css"
import "fontsource-noto-sans-kr/100.css"
import "fontsource-noto-sans-kr/300.css"
import "fontsource-noto-sans-kr/400.css"
import "fontsource-noto-sans-kr/500.css"
import "fontsource-noto-sans-kr/700.css"
import "fontsource-noto-sans-kr/900.css"